services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - ${API_PORT:-8080}:8080
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: http://+:8080
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      ConnectionStrings__DefaultConnection: "User ID=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres};Host=${DB_HOST:-database};Port=${DB_PORT:-5432};Database=${POSTGRES_DB:-mandys};"
    volumes:
      - .:/src
      - /src/Mandys.Api/bin
      - /src/Mandys.Api/obj
      - /src/Mandys.Application/bin
      - /src/Mandys.Application/obj
      - /src/Mandys.Domain/bin
      - /src/Mandys.Domain/obj
      - /src/Mandys.Infrastructure/bin
      - /src/Mandys.Infrastructure/obj
